require_relative 'find_by_method_mode_with_authentication_method_modes_response'
module MicrosoftGraphBeta::Policies::AuthenticationStrengthPolicies::FindByMethodModeWithAuthenticationMethodModes
end
