require_relative 'download_apple_push_notification_certificate_signing_request_response'
module MicrosoftGraphBeta::DeviceManagement::ApplePushNotificationCertificate::MicrosoftGraphDownloadApplePushNotificationCertificateSigningRequest
end
