module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageResources::Item::AccessPackageResourceRoles::Item::AccessPackageResource::AccessPackageResourceScopes::Item::AccessPackageResource::AccessPackageResourceEnvironment
end
