require_relative 'get_recent_notebooks_with_include_personal_notebooks_response'
module MicrosoftGraphBeta::Sites::Item::Onenote::Notebooks::MicrosoftGraphGetRecentNotebooksWithIncludePersonalNotebooks
end
