require_relative 'additional_access_with_access_package_id_with_incompatible_access_package_id_response'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::AdditionalAccessWithAccessPackageIdWithIncompatibleAccessPackageId
end
