module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceRole::AccessPackageResource::AccessPackageResourceScopes::Item
end
