require_relative 'tenant_search_post_request_body'
require_relative 'tenant_search_response'
module MicrosoftGraphBeta::TenantRelationships::ManagedTenants::TenantGroups::MicrosoftGraphManagedTenantsTenantSearch
end
