require_relative 'create_migration_report_post_request_body'
require_relative 'create_migration_report_response'
module MicrosoftGraphBeta::DeviceManagement::GroupPolicyMigrationReports::MicrosoftGraphCreateMigrationReport
end
