require_relative 'get_by_ids_post_request_body'
require_relative 'get_by_ids_response'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::ConnectedOrganizations::Item::ExternalSponsors::MicrosoftGraphGetByIds
end
