require_relative 'get_user_owned_objects_post_request_body'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::ConnectedOrganizations::Item::InternalSponsors::MicrosoftGraphGetUserOwnedObjects
end
