module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageCatalogs::Item::AccessPackageResourceRoles::Item::AccessPackageResource::AccessPackageResourceScopes::Item::AccessPackageResource::AccessPackageResourceEnvironment
end
