require_relative 'import_office365_device_configuration_policies_response'
module MicrosoftGraphBeta::DeviceManagement::Templates::Item::MigratableTo::MicrosoftGraphImportOffice365DeviceConfigurationPolicies
end
