require_relative 'get_direct_routing_calls_with_from_date_time_with_to_date_time_response'
module MicrosoftGraphBeta::Communications::CallRecords::MicrosoftGraphCallRecordsGetDirectRoutingCallsWithFromDateTimeWithToDateTime
end
