require_relative 'get_health_metric_time_series_post_request_body'
require_relative 'get_health_metric_time_series_response'
module MicrosoftGraphBeta::DeviceManagement::MicrosoftTunnelSites::Item::MicrosoftTunnelServers::Item::MicrosoftGraphGetHealthMetricTimeSeries
end
