require_relative 'initiate_on_demand_proactive_remediation_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::ComanagedDevices::Item::MicrosoftGraphInitiateOnDemandProactiveRemediation
end
