require_relative 'update_scope_tags_post_request_body'
require_relative 'update_scope_tags_response'
module MicrosoftGraphBeta::DeviceManagement::GroupPolicyMigrationReports::Item::MicrosoftGraphUpdateScopeTags
end
