require_relative 'evaluate_application_post_request_body'
require_relative 'evaluate_application_response'
module MicrosoftGraphBeta::Security::InformationProtection::SensitivityLabels::EvaluateApplication
end
