module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackage::AccessPackageResourceRoleScopes::Item::AccessPackageResourceScope::AccessPackageResource
end
