require_relative 'move_to_catalog_post_request_body'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackage::MicrosoftGraphMoveToCatalog
end
