require_relative 'get_group_policy_settings_device_settings_report_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::Reports::MicrosoftGraphGetGroupPolicySettingsDeviceSettingsReport
end
