require_relative 'get_expiring_vpp_token_count_with_expiring_before_date_time_response'
module MicrosoftGraphBeta::DeviceManagement::DepOnboardingSettings::GetExpiringVppTokenCountWithExpiringBeforeDateTime
end
