module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackages::Item::AccessPackageResourceRoleScopes::Item::AccessPackageResourceRole::AccessPackageResource::AccessPackageResourceScopes::Item::AccessPackageResource::AccessPackageResourceRoles
end
