require_relative 'get_windows_quality_update_alerts_per_policy_per_device_report_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::Reports::MicrosoftGraphGetWindowsQualityUpdateAlertsPerPolicyPerDeviceReport
end
