require_relative 'get_total_aggregated_remote_connection_reports_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::VirtualEndpoint::Reports::GetTotalAggregatedRemoteConnectionReports
end
