require_relative 'evaluate_removal_post_request_body'
require_relative 'evaluate_removal_response'
module MicrosoftGraphBeta::Users::Item::Security::InformationProtection::SensitivityLabels::MicrosoftGraphSecurityEvaluateRemoval
end
