require 'microsoft_kiota_abstractions'
require_relative '../microsoft_graph_beta'
require_relative './models'

module MicrosoftGraphBeta
    module Models
        class CloudPcProvisioningPolicy < MicrosoftGraphBeta::Models::Entity
            include MicrosoftKiotaAbstractions::Parsable
            ## 
            # The URL of the alternate resource that links to this provisioning policy. Read-only.
            @alternate_resource_url
            ## 
            # A defined collection of provisioning policy assignments. Represents the set of Microsoft 365 groups and security groups in Microsoft Entra ID that have provisioning policy assigned. Returned only on $expand. For an example about how to get the assignments relationship, see Get cloudPcProvisioningPolicy.
            @assignments
            ## 
            # The display name of the Cloud PC group that the Cloud PCs reside in. Read-only.
            @cloud_pc_group_display_name
            ## 
            # The template used to name Cloud PCs provisioned using this policy. The template can contain custom text and replacement tokens, including %USERNAME:x% and %RAND:x%, which represent the user's name and a randomly generated number, respectively. For example, CPC-%USERNAME:4%-%RAND:5% means that the name of the Cloud PC starts with CPC-, followed by a four-character username, a - character, and then five random characters. The total length of the text generated by the template can't exceed 15 characters. Supports $filter, $select, and $orderby.
            @cloud_pc_naming_template
            ## 
            # The provisioning policy description. Supports $filter, $select, and $orderBy.
            @description
            ## 
            # The display name for the provisioning policy.
            @display_name
            ## 
            # The domainJoinConfiguration property
            @domain_join_configuration
            ## 
            # Specifies a list ordered by priority on how Cloud PCs join Microsoft Entra ID (Azure AD). Supports $select.
            @domain_join_configurations
            ## 
            # True if single sign-on can access the provisioned Cloud PC. False indicates that the provisioned Cloud PC doesn't support this feature. The default value is false. Windows 365 users can use single sign-on to authenticate to Microsoft Entra ID with passwordless options (for example, FIDO keys) to access their Cloud PC. Optional.
            @enable_single_sign_on
            ## 
            # The number of hours to wait before reprovisioning/deprovisioning happens. Read-only.
            @grace_period_in_hours
            ## 
            # The display name of the operating system image that is used for provisioning. For example, Windows 11 Preview + Microsoft 365 Apps 23H2 23H2. Supports $filter, $select, and $orderBy.
            @image_display_name
            ## 
            # The unique identifier that represents an operating system image that is used for provisioning new Cloud PCs. The format for a gallery type image is: {publisherNameofferNameskuName}. Supported values for each of the parameters are:publisher: Microsoftwindowsdesktop offer: windows-ent-cpc sku: 21h1-ent-cpc-m365, 21h1-ent-cpc-os, 20h2-ent-cpc-m365, 20h2-ent-cpc-os, 20h1-ent-cpc-m365, 20h1-ent-cpc-os, 19h2-ent-cpc-m365, and 19h2-ent-cpc-os Supports $filter, $select, and $orderBy.
            @image_id
            ## 
            # The imageType property
            @image_type
            ## 
            # When true, the local admin is enabled for Cloud PCs; false indicates that the local admin isn't enabled for Cloud PCs. The default value is false. Supports $filter, $select, and $orderBy.
            @local_admin_enabled
            ## 
            # The managedBy property
            @managed_by
            ## 
            # The specific settings to microsoftManagedDesktop that enables Microsoft Managed Desktop customers to get device managed experience for Cloud PC. To enable microsoftManagedDesktop to provide more value, an admin needs to specify certain settings in it. Supports $filter, $select, and $orderBy.
            @microsoft_managed_desktop
            ## 
            # The onPremisesConnectionId property
            @on_premises_connection_id
            ## 
            # Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. The possible values are dedicated, shared, unknownFutureValue, sharedByUser, sharedByEntraGroup. You must use the Prefer: include-unknown-enum-members request header to get the following values from this evolvable enum: sharedByUser, sharedByEntraGroup. The shared member is deprecated and will stop returning on April 30, 2027; going forward, use the sharedByUser member. For example, a dedicated service plan can be assigned to only one user and provision only one Cloud PC. The shared and sharedByUser plans require customers to purchase a shared service plan. Each shared license purchased can enable up to three Cloud PCs, with only one user signed in at a time. The sharedByEntraGroup plan also requires the purchase of a shared service plan. Each shared license under this plan can enable one Cloud PC, which is shared for the group according to the assignments of this policy. By default, the license type is dedicated if the provisioningType isn't specified when you create the cloudPcProvisioningPolicy. You can't change this property after the cloudPcProvisioningPolicy is created.
            @provisioning_type
            ## 
            # The scopeIds property
            @scope_ids
            ## 
            # Indicates a specific Windows setting to configure during the creation of Cloud PCs for this provisioning policy. Supports $select.
            @windows_setting
            ## 
            # The windowsSettings property
            @windows_settings
            ## 
            ## Gets the alternateResourceUrl property value. The URL of the alternate resource that links to this provisioning policy. Read-only.
            ## @return a string
            ## 
            def alternate_resource_url
                return @alternate_resource_url
            end
            ## 
            ## Sets the alternateResourceUrl property value. The URL of the alternate resource that links to this provisioning policy. Read-only.
            ## @param value Value to set for the alternateResourceUrl property.
            ## @return a void
            ## 
            def alternate_resource_url=(value)
                @alternate_resource_url = value
            end
            ## 
            ## Gets the assignments property value. A defined collection of provisioning policy assignments. Represents the set of Microsoft 365 groups and security groups in Microsoft Entra ID that have provisioning policy assigned. Returned only on $expand. For an example about how to get the assignments relationship, see Get cloudPcProvisioningPolicy.
            ## @return a cloud_pc_provisioning_policy_assignment
            ## 
            def assignments
                return @assignments
            end
            ## 
            ## Sets the assignments property value. A defined collection of provisioning policy assignments. Represents the set of Microsoft 365 groups and security groups in Microsoft Entra ID that have provisioning policy assigned. Returned only on $expand. For an example about how to get the assignments relationship, see Get cloudPcProvisioningPolicy.
            ## @param value Value to set for the assignments property.
            ## @return a void
            ## 
            def assignments=(value)
                @assignments = value
            end
            ## 
            ## Gets the cloudPcGroupDisplayName property value. The display name of the Cloud PC group that the Cloud PCs reside in. Read-only.
            ## @return a string
            ## 
            def cloud_pc_group_display_name
                return @cloud_pc_group_display_name
            end
            ## 
            ## Sets the cloudPcGroupDisplayName property value. The display name of the Cloud PC group that the Cloud PCs reside in. Read-only.
            ## @param value Value to set for the cloudPcGroupDisplayName property.
            ## @return a void
            ## 
            def cloud_pc_group_display_name=(value)
                @cloud_pc_group_display_name = value
            end
            ## 
            ## Gets the cloudPcNamingTemplate property value. The template used to name Cloud PCs provisioned using this policy. The template can contain custom text and replacement tokens, including %USERNAME:x% and %RAND:x%, which represent the user's name and a randomly generated number, respectively. For example, CPC-%USERNAME:4%-%RAND:5% means that the name of the Cloud PC starts with CPC-, followed by a four-character username, a - character, and then five random characters. The total length of the text generated by the template can't exceed 15 characters. Supports $filter, $select, and $orderby.
            ## @return a string
            ## 
            def cloud_pc_naming_template
                return @cloud_pc_naming_template
            end
            ## 
            ## Sets the cloudPcNamingTemplate property value. The template used to name Cloud PCs provisioned using this policy. The template can contain custom text and replacement tokens, including %USERNAME:x% and %RAND:x%, which represent the user's name and a randomly generated number, respectively. For example, CPC-%USERNAME:4%-%RAND:5% means that the name of the Cloud PC starts with CPC-, followed by a four-character username, a - character, and then five random characters. The total length of the text generated by the template can't exceed 15 characters. Supports $filter, $select, and $orderby.
            ## @param value Value to set for the cloudPcNamingTemplate property.
            ## @return a void
            ## 
            def cloud_pc_naming_template=(value)
                @cloud_pc_naming_template = value
            end
            ## 
            ## Instantiates a new CloudPcProvisioningPolicy and sets the default values.
            ## @return a void
            ## 
            def initialize()
                super
            end
            ## 
            ## Creates a new instance of the appropriate class based on discriminator value
            ## @param parse_node The parse node to use to read the discriminator value and create the object
            ## @return a cloud_pc_provisioning_policy
            ## 
            def self.create_from_discriminator_value(parse_node)
                raise StandardError, 'parse_node cannot be null' if parse_node.nil?
                return CloudPcProvisioningPolicy.new
            end
            ## 
            ## Gets the description property value. The provisioning policy description. Supports $filter, $select, and $orderBy.
            ## @return a string
            ## 
            def description
                return @description
            end
            ## 
            ## Sets the description property value. The provisioning policy description. Supports $filter, $select, and $orderBy.
            ## @param value Value to set for the description property.
            ## @return a void
            ## 
            def description=(value)
                @description = value
            end
            ## 
            ## Gets the displayName property value. The display name for the provisioning policy.
            ## @return a string
            ## 
            def display_name
                return @display_name
            end
            ## 
            ## Sets the displayName property value. The display name for the provisioning policy.
            ## @param value Value to set for the displayName property.
            ## @return a void
            ## 
            def display_name=(value)
                @display_name = value
            end
            ## 
            ## Gets the domainJoinConfiguration property value. The domainJoinConfiguration property
            ## @return a cloud_pc_domain_join_configuration
            ## 
            def domain_join_configuration
                return @domain_join_configuration
            end
            ## 
            ## Sets the domainJoinConfiguration property value. The domainJoinConfiguration property
            ## @param value Value to set for the domainJoinConfiguration property.
            ## @return a void
            ## 
            def domain_join_configuration=(value)
                @domain_join_configuration = value
            end
            ## 
            ## Gets the domainJoinConfigurations property value. Specifies a list ordered by priority on how Cloud PCs join Microsoft Entra ID (Azure AD). Supports $select.
            ## @return a cloud_pc_domain_join_configuration
            ## 
            def domain_join_configurations
                return @domain_join_configurations
            end
            ## 
            ## Sets the domainJoinConfigurations property value. Specifies a list ordered by priority on how Cloud PCs join Microsoft Entra ID (Azure AD). Supports $select.
            ## @param value Value to set for the domainJoinConfigurations property.
            ## @return a void
            ## 
            def domain_join_configurations=(value)
                @domain_join_configurations = value
            end
            ## 
            ## Gets the enableSingleSignOn property value. True if single sign-on can access the provisioned Cloud PC. False indicates that the provisioned Cloud PC doesn't support this feature. The default value is false. Windows 365 users can use single sign-on to authenticate to Microsoft Entra ID with passwordless options (for example, FIDO keys) to access their Cloud PC. Optional.
            ## @return a boolean
            ## 
            def enable_single_sign_on
                return @enable_single_sign_on
            end
            ## 
            ## Sets the enableSingleSignOn property value. True if single sign-on can access the provisioned Cloud PC. False indicates that the provisioned Cloud PC doesn't support this feature. The default value is false. Windows 365 users can use single sign-on to authenticate to Microsoft Entra ID with passwordless options (for example, FIDO keys) to access their Cloud PC. Optional.
            ## @param value Value to set for the enableSingleSignOn property.
            ## @return a void
            ## 
            def enable_single_sign_on=(value)
                @enable_single_sign_on = value
            end
            ## 
            ## The deserialization information for the current model
            ## @return a i_dictionary
            ## 
            def get_field_deserializers()
                return super.merge({
                    "alternateResourceUrl" => lambda {|n| @alternate_resource_url = n.get_string_value() },
                    "assignments" => lambda {|n| @assignments = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::CloudPcProvisioningPolicyAssignment.create_from_discriminator_value(pn) }) },
                    "cloudPcGroupDisplayName" => lambda {|n| @cloud_pc_group_display_name = n.get_string_value() },
                    "cloudPcNamingTemplate" => lambda {|n| @cloud_pc_naming_template = n.get_string_value() },
                    "description" => lambda {|n| @description = n.get_string_value() },
                    "displayName" => lambda {|n| @display_name = n.get_string_value() },
                    "domainJoinConfiguration" => lambda {|n| @domain_join_configuration = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::CloudPcDomainJoinConfiguration.create_from_discriminator_value(pn) }) },
                    "domainJoinConfigurations" => lambda {|n| @domain_join_configurations = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::CloudPcDomainJoinConfiguration.create_from_discriminator_value(pn) }) },
                    "enableSingleSignOn" => lambda {|n| @enable_single_sign_on = n.get_boolean_value() },
                    "gracePeriodInHours" => lambda {|n| @grace_period_in_hours = n.get_number_value() },
                    "imageDisplayName" => lambda {|n| @image_display_name = n.get_string_value() },
                    "imageId" => lambda {|n| @image_id = n.get_string_value() },
                    "imageType" => lambda {|n| @image_type = n.get_enum_value(MicrosoftGraphBeta::Models::CloudPcProvisioningPolicyImageType) },
                    "localAdminEnabled" => lambda {|n| @local_admin_enabled = n.get_boolean_value() },
                    "managedBy" => lambda {|n| @managed_by = n.get_enum_values(MicrosoftGraphBeta::Models::CloudPcManagementService) },
                    "microsoftManagedDesktop" => lambda {|n| @microsoft_managed_desktop = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::MicrosoftManagedDesktop.create_from_discriminator_value(pn) }) },
                    "onPremisesConnectionId" => lambda {|n| @on_premises_connection_id = n.get_string_value() },
                    "provisioningType" => lambda {|n| @provisioning_type = n.get_enum_value(MicrosoftGraphBeta::Models::CloudPcProvisioningType) },
                    "scopeIds" => lambda {|n| @scope_ids = n.get_collection_of_primitive_values(String) },
                    "windowsSetting" => lambda {|n| @windows_setting = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::CloudPcWindowsSetting.create_from_discriminator_value(pn) }) },
                    "windowsSettings" => lambda {|n| @windows_settings = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::CloudPcWindowsSettings.create_from_discriminator_value(pn) }) },
                })
            end
            ## 
            ## Gets the gracePeriodInHours property value. The number of hours to wait before reprovisioning/deprovisioning happens. Read-only.
            ## @return a integer
            ## 
            def grace_period_in_hours
                return @grace_period_in_hours
            end
            ## 
            ## Sets the gracePeriodInHours property value. The number of hours to wait before reprovisioning/deprovisioning happens. Read-only.
            ## @param value Value to set for the gracePeriodInHours property.
            ## @return a void
            ## 
            def grace_period_in_hours=(value)
                @grace_period_in_hours = value
            end
            ## 
            ## Gets the imageDisplayName property value. The display name of the operating system image that is used for provisioning. For example, Windows 11 Preview + Microsoft 365 Apps 23H2 23H2. Supports $filter, $select, and $orderBy.
            ## @return a string
            ## 
            def image_display_name
                return @image_display_name
            end
            ## 
            ## Sets the imageDisplayName property value. The display name of the operating system image that is used for provisioning. For example, Windows 11 Preview + Microsoft 365 Apps 23H2 23H2. Supports $filter, $select, and $orderBy.
            ## @param value Value to set for the imageDisplayName property.
            ## @return a void
            ## 
            def image_display_name=(value)
                @image_display_name = value
            end
            ## 
            ## Gets the imageId property value. The unique identifier that represents an operating system image that is used for provisioning new Cloud PCs. The format for a gallery type image is: {publisherNameofferNameskuName}. Supported values for each of the parameters are:publisher: Microsoftwindowsdesktop offer: windows-ent-cpc sku: 21h1-ent-cpc-m365, 21h1-ent-cpc-os, 20h2-ent-cpc-m365, 20h2-ent-cpc-os, 20h1-ent-cpc-m365, 20h1-ent-cpc-os, 19h2-ent-cpc-m365, and 19h2-ent-cpc-os Supports $filter, $select, and $orderBy.
            ## @return a string
            ## 
            def image_id
                return @image_id
            end
            ## 
            ## Sets the imageId property value. The unique identifier that represents an operating system image that is used for provisioning new Cloud PCs. The format for a gallery type image is: {publisherNameofferNameskuName}. Supported values for each of the parameters are:publisher: Microsoftwindowsdesktop offer: windows-ent-cpc sku: 21h1-ent-cpc-m365, 21h1-ent-cpc-os, 20h2-ent-cpc-m365, 20h2-ent-cpc-os, 20h1-ent-cpc-m365, 20h1-ent-cpc-os, 19h2-ent-cpc-m365, and 19h2-ent-cpc-os Supports $filter, $select, and $orderBy.
            ## @param value Value to set for the imageId property.
            ## @return a void
            ## 
            def image_id=(value)
                @image_id = value
            end
            ## 
            ## Gets the imageType property value. The imageType property
            ## @return a cloud_pc_provisioning_policy_image_type
            ## 
            def image_type
                return @image_type
            end
            ## 
            ## Sets the imageType property value. The imageType property
            ## @param value Value to set for the imageType property.
            ## @return a void
            ## 
            def image_type=(value)
                @image_type = value
            end
            ## 
            ## Gets the localAdminEnabled property value. When true, the local admin is enabled for Cloud PCs; false indicates that the local admin isn't enabled for Cloud PCs. The default value is false. Supports $filter, $select, and $orderBy.
            ## @return a boolean
            ## 
            def local_admin_enabled
                return @local_admin_enabled
            end
            ## 
            ## Sets the localAdminEnabled property value. When true, the local admin is enabled for Cloud PCs; false indicates that the local admin isn't enabled for Cloud PCs. The default value is false. Supports $filter, $select, and $orderBy.
            ## @param value Value to set for the localAdminEnabled property.
            ## @return a void
            ## 
            def local_admin_enabled=(value)
                @local_admin_enabled = value
            end
            ## 
            ## Gets the managedBy property value. The managedBy property
            ## @return a cloud_pc_management_service
            ## 
            def managed_by
                return @managed_by
            end
            ## 
            ## Sets the managedBy property value. The managedBy property
            ## @param value Value to set for the managedBy property.
            ## @return a void
            ## 
            def managed_by=(value)
                @managed_by = value
            end
            ## 
            ## Gets the microsoftManagedDesktop property value. The specific settings to microsoftManagedDesktop that enables Microsoft Managed Desktop customers to get device managed experience for Cloud PC. To enable microsoftManagedDesktop to provide more value, an admin needs to specify certain settings in it. Supports $filter, $select, and $orderBy.
            ## @return a microsoft_managed_desktop
            ## 
            def microsoft_managed_desktop
                return @microsoft_managed_desktop
            end
            ## 
            ## Sets the microsoftManagedDesktop property value. The specific settings to microsoftManagedDesktop that enables Microsoft Managed Desktop customers to get device managed experience for Cloud PC. To enable microsoftManagedDesktop to provide more value, an admin needs to specify certain settings in it. Supports $filter, $select, and $orderBy.
            ## @param value Value to set for the microsoftManagedDesktop property.
            ## @return a void
            ## 
            def microsoft_managed_desktop=(value)
                @microsoft_managed_desktop = value
            end
            ## 
            ## Gets the onPremisesConnectionId property value. The onPremisesConnectionId property
            ## @return a string
            ## 
            def on_premises_connection_id
                return @on_premises_connection_id
            end
            ## 
            ## Sets the onPremisesConnectionId property value. The onPremisesConnectionId property
            ## @param value Value to set for the onPremisesConnectionId property.
            ## @return a void
            ## 
            def on_premises_connection_id=(value)
                @on_premises_connection_id = value
            end
            ## 
            ## Gets the provisioningType property value. Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. The possible values are dedicated, shared, unknownFutureValue, sharedByUser, sharedByEntraGroup. You must use the Prefer: include-unknown-enum-members request header to get the following values from this evolvable enum: sharedByUser, sharedByEntraGroup. The shared member is deprecated and will stop returning on April 30, 2027; going forward, use the sharedByUser member. For example, a dedicated service plan can be assigned to only one user and provision only one Cloud PC. The shared and sharedByUser plans require customers to purchase a shared service plan. Each shared license purchased can enable up to three Cloud PCs, with only one user signed in at a time. The sharedByEntraGroup plan also requires the purchase of a shared service plan. Each shared license under this plan can enable one Cloud PC, which is shared for the group according to the assignments of this policy. By default, the license type is dedicated if the provisioningType isn't specified when you create the cloudPcProvisioningPolicy. You can't change this property after the cloudPcProvisioningPolicy is created.
            ## @return a cloud_pc_provisioning_type
            ## 
            def provisioning_type
                return @provisioning_type
            end
            ## 
            ## Sets the provisioningType property value. Specifies the type of licenses to be used when provisioning Cloud PCs using this policy. The possible values are dedicated, shared, unknownFutureValue, sharedByUser, sharedByEntraGroup. You must use the Prefer: include-unknown-enum-members request header to get the following values from this evolvable enum: sharedByUser, sharedByEntraGroup. The shared member is deprecated and will stop returning on April 30, 2027; going forward, use the sharedByUser member. For example, a dedicated service plan can be assigned to only one user and provision only one Cloud PC. The shared and sharedByUser plans require customers to purchase a shared service plan. Each shared license purchased can enable up to three Cloud PCs, with only one user signed in at a time. The sharedByEntraGroup plan also requires the purchase of a shared service plan. Each shared license under this plan can enable one Cloud PC, which is shared for the group according to the assignments of this policy. By default, the license type is dedicated if the provisioningType isn't specified when you create the cloudPcProvisioningPolicy. You can't change this property after the cloudPcProvisioningPolicy is created.
            ## @param value Value to set for the provisioningType property.
            ## @return a void
            ## 
            def provisioning_type=(value)
                @provisioning_type = value
            end
            ## 
            ## Gets the scopeIds property value. The scopeIds property
            ## @return a string
            ## 
            def scope_ids
                return @scope_ids
            end
            ## 
            ## Sets the scopeIds property value. The scopeIds property
            ## @param value Value to set for the scopeIds property.
            ## @return a void
            ## 
            def scope_ids=(value)
                @scope_ids = value
            end
            ## 
            ## Serializes information the current object
            ## @param writer Serialization writer to use to serialize this model
            ## @return a void
            ## 
            def serialize(writer)
                raise StandardError, 'writer cannot be null' if writer.nil?
                super
                writer.write_string_value("alternateResourceUrl", @alternate_resource_url)
                writer.write_collection_of_object_values("assignments", @assignments)
                writer.write_string_value("cloudPcGroupDisplayName", @cloud_pc_group_display_name)
                writer.write_string_value("cloudPcNamingTemplate", @cloud_pc_naming_template)
                writer.write_string_value("description", @description)
                writer.write_string_value("displayName", @display_name)
                writer.write_object_value("domainJoinConfiguration", @domain_join_configuration)
                writer.write_collection_of_object_values("domainJoinConfigurations", @domain_join_configurations)
                writer.write_boolean_value("enableSingleSignOn", @enable_single_sign_on)
                writer.write_number_value("gracePeriodInHours", @grace_period_in_hours)
                writer.write_string_value("imageDisplayName", @image_display_name)
                writer.write_string_value("imageId", @image_id)
                writer.write_enum_value("imageType", @image_type)
                writer.write_boolean_value("localAdminEnabled", @local_admin_enabled)
                writer.write_enum_value("managedBy", @managed_by)
                writer.write_object_value("microsoftManagedDesktop", @microsoft_managed_desktop)
                writer.write_string_value("onPremisesConnectionId", @on_premises_connection_id)
                writer.write_enum_value("provisioningType", @provisioning_type)
                writer.write_collection_of_primitive_values("scopeIds", @scope_ids)
                writer.write_object_value("windowsSetting", @windows_setting)
                writer.write_object_value("windowsSettings", @windows_settings)
            end
            ## 
            ## Gets the windowsSetting property value. Indicates a specific Windows setting to configure during the creation of Cloud PCs for this provisioning policy. Supports $select.
            ## @return a cloud_pc_windows_setting
            ## 
            def windows_setting
                return @windows_setting
            end
            ## 
            ## Sets the windowsSetting property value. Indicates a specific Windows setting to configure during the creation of Cloud PCs for this provisioning policy. Supports $select.
            ## @param value Value to set for the windowsSetting property.
            ## @return a void
            ## 
            def windows_setting=(value)
                @windows_setting = value
            end
            ## 
            ## Gets the windowsSettings property value. The windowsSettings property
            ## @return a cloud_pc_windows_settings
            ## 
            def windows_settings
                return @windows_settings
            end
            ## 
            ## Sets the windowsSettings property value. The windowsSettings property
            ## @param value Value to set for the windowsSettings property.
            ## @return a void
            ## 
            def windows_settings=(value)
                @windows_settings = value
            end
        end
    end
end
