module MicrosoftGraphBeta::Models
    CloudPcRegionGroup = {
        Default: :Default,
        Australia: :Australia,
        Canada: :Canada,
        UsCentral: :UsCentral,
        UsEast: :UsEast,
        UsWest: :UsWest,
        France: :France,
        Germany: :Germany,
        EuropeUnion: :EuropeUnion,
        UnitedKingdom: :UnitedKingdom,
        Japan: :Japan,
        Asia: :Asia,
        India: :India,
        SouthAmerica: :SouthAmerica,
        Euap: :Euap,
        UsGovernment: :UsGovernment,
        UsGovernmentDOD: :UsGovernmentDOD,
        UnknownFutureValue: :UnknownFutureValue,
        Norway: :Norway,
        Switzerland: :Switzerland,
        SouthKorea: :SouthKorea,
    }
end
