module MicrosoftGraphBeta
    module Models
        ConditionalAccessRule = {
            AllApps: :AllApps,
            FirstPartyApps: :FirstPartyApps,
            Office365: :Office365,
            AppId: :AppId,
            Acr: :Acr,
            AppFilter: :AppFilter,
            AllUsers: :AllUsers,
            Guest: :Guest,
            GroupId: :GroupId,
            RoleId: :RoleId,
            UserId: :UserId,
            AllDevicePlatforms: :AllDevicePlatforms,
            DevicePlatform: :DevicePlatform,
            AllLocations: :AllLocations,
            InsideCorpnet: :InsideCorpnet,
            AllTrustedLocations: :AllTrustedLocations,
            LocationId: :LocationId,
            AllDevices: :AllDevices,
            DeviceFilter: :DeviceFilter,
            DeviceState: :DeviceState,
            UnknownFutureValue: :UnknownFutureValue,
            DeviceFilterIncludeRuleNotMatched: :DeviceFilterIncludeRuleNotMatched,
            AllDeviceStates: :AllDeviceStates,
            AnonymizedIPAddress: :AnonymizedIPAddress,
            UnfamiliarFeatures: :UnfamiliarFeatures,
            NationStateIPAddress: :NationStateIPAddress,
            RealTimeThreatIntelligence: :RealTimeThreatIntelligence,
            InternalGuest: :InternalGuest,
            B2bCollaborationGuest: :B2bCollaborationGuest,
            B2bCollaborationMember: :B2bCollaborationMember,
            B2bDirectConnectUser: :B2bDirectConnectUser,
            OtherExternalUser: :OtherExternalUser,
            ServiceProvider: :ServiceProvider,
        }
    end
end
