require 'microsoft_kiota_abstractions'
require_relative '../microsoft_graph_beta'
require_relative './models'

module MicrosoftGraphBeta
    module Models
        class IndustryDataAggregatedInboundStatistics
            include MicrosoftKiotaAbstractions::AdditionalDataHolder, MicrosoftKiotaAbstractions::Parsable
            ## 
            # Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            @additional_data
            ## 
            # The aggregate count of errors encountered by activities during this run.
            @errors
            ## 
            # The aggregate count of active inbound groups processed during the run.
            @groups
            ## 
            # The aggregate count of active people matched to an Azure Active Directory user, by role.
            @matched_people_by_role
            ## 
            # The aggregate count of active inbound memberships processed during the run.
            @memberships
            ## 
            # The OdataType property
            @odata_type
            ## 
            # The aggregate count of active inbound organizations processed during the run.
            @organizations
            ## 
            # The aggregate count of active inbound people processed during the run.
            @people
            ## 
            # The aggregate count of active people not matched to an Azure Active Directory user, by role.
            @unmatched_people_by_role
            ## 
            # The aggregate count of warnings generated by activities during this run.
            @warnings
            ## 
            ## Gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            ## @return a i_dictionary
            ## 
            def additional_data
                return @additional_data
            end
            ## 
            ## Sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            ## @param value Value to set for the AdditionalData property.
            ## @return a void
            ## 
            def additional_data=(value)
                @additional_data = value
            end
            ## 
            ## Instantiates a new industryDataAggregatedInboundStatistics and sets the default values.
            ## @return a void
            ## 
            def initialize()
                @additional_data = Hash.new
            end
            ## 
            ## Creates a new instance of the appropriate class based on discriminator value
            ## @param parse_node The parse node to use to read the discriminator value and create the object
            ## @return a industry_data_aggregated_inbound_statistics
            ## 
            def self.create_from_discriminator_value(parse_node)
                raise StandardError, 'parse_node cannot be null' if parse_node.nil?
                return IndustryDataAggregatedInboundStatistics.new
            end
            ## 
            ## Gets the errors property value. The aggregate count of errors encountered by activities during this run.
            ## @return a integer
            ## 
            def errors
                return @errors
            end
            ## 
            ## Sets the errors property value. The aggregate count of errors encountered by activities during this run.
            ## @param value Value to set for the errors property.
            ## @return a void
            ## 
            def errors=(value)
                @errors = value
            end
            ## 
            ## The deserialization information for the current model
            ## @return a i_dictionary
            ## 
            def get_field_deserializers()
                return {
                    "errors" => lambda {|n| @errors = n.get_number_value() },
                    "groups" => lambda {|n| @groups = n.get_number_value() },
                    "matchedPeopleByRole" => lambda {|n| @matched_people_by_role = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::IndustryDataIndustryDataRunRoleCountMetric.create_from_discriminator_value(pn) }) },
                    "memberships" => lambda {|n| @memberships = n.get_number_value() },
                    "@odata.type" => lambda {|n| @odata_type = n.get_string_value() },
                    "organizations" => lambda {|n| @organizations = n.get_number_value() },
                    "people" => lambda {|n| @people = n.get_number_value() },
                    "unmatchedPeopleByRole" => lambda {|n| @unmatched_people_by_role = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::IndustryDataIndustryDataRunRoleCountMetric.create_from_discriminator_value(pn) }) },
                    "warnings" => lambda {|n| @warnings = n.get_number_value() },
                }
            end
            ## 
            ## Gets the groups property value. The aggregate count of active inbound groups processed during the run.
            ## @return a integer
            ## 
            def groups
                return @groups
            end
            ## 
            ## Sets the groups property value. The aggregate count of active inbound groups processed during the run.
            ## @param value Value to set for the groups property.
            ## @return a void
            ## 
            def groups=(value)
                @groups = value
            end
            ## 
            ## Gets the matchedPeopleByRole property value. The aggregate count of active people matched to an Azure Active Directory user, by role.
            ## @return a industry_data_industry_data_run_role_count_metric
            ## 
            def matched_people_by_role
                return @matched_people_by_role
            end
            ## 
            ## Sets the matchedPeopleByRole property value. The aggregate count of active people matched to an Azure Active Directory user, by role.
            ## @param value Value to set for the matchedPeopleByRole property.
            ## @return a void
            ## 
            def matched_people_by_role=(value)
                @matched_people_by_role = value
            end
            ## 
            ## Gets the memberships property value. The aggregate count of active inbound memberships processed during the run.
            ## @return a integer
            ## 
            def memberships
                return @memberships
            end
            ## 
            ## Sets the memberships property value. The aggregate count of active inbound memberships processed during the run.
            ## @param value Value to set for the memberships property.
            ## @return a void
            ## 
            def memberships=(value)
                @memberships = value
            end
            ## 
            ## Gets the @odata.type property value. The OdataType property
            ## @return a string
            ## 
            def odata_type
                return @odata_type
            end
            ## 
            ## Sets the @odata.type property value. The OdataType property
            ## @param value Value to set for the @odata.type property.
            ## @return a void
            ## 
            def odata_type=(value)
                @odata_type = value
            end
            ## 
            ## Gets the organizations property value. The aggregate count of active inbound organizations processed during the run.
            ## @return a integer
            ## 
            def organizations
                return @organizations
            end
            ## 
            ## Sets the organizations property value. The aggregate count of active inbound organizations processed during the run.
            ## @param value Value to set for the organizations property.
            ## @return a void
            ## 
            def organizations=(value)
                @organizations = value
            end
            ## 
            ## Gets the people property value. The aggregate count of active inbound people processed during the run.
            ## @return a integer
            ## 
            def people
                return @people
            end
            ## 
            ## Sets the people property value. The aggregate count of active inbound people processed during the run.
            ## @param value Value to set for the people property.
            ## @return a void
            ## 
            def people=(value)
                @people = value
            end
            ## 
            ## Serializes information the current object
            ## @param writer Serialization writer to use to serialize this model
            ## @return a void
            ## 
            def serialize(writer)
                raise StandardError, 'writer cannot be null' if writer.nil?
                writer.write_string_value("@odata.type", @odata_type)
                writer.write_additional_data(@additional_data)
            end
            ## 
            ## Gets the unmatchedPeopleByRole property value. The aggregate count of active people not matched to an Azure Active Directory user, by role.
            ## @return a industry_data_industry_data_run_role_count_metric
            ## 
            def unmatched_people_by_role
                return @unmatched_people_by_role
            end
            ## 
            ## Sets the unmatchedPeopleByRole property value. The aggregate count of active people not matched to an Azure Active Directory user, by role.
            ## @param value Value to set for the unmatchedPeopleByRole property.
            ## @return a void
            ## 
            def unmatched_people_by_role=(value)
                @unmatched_people_by_role = value
            end
            ## 
            ## Gets the warnings property value. The aggregate count of warnings generated by activities during this run.
            ## @return a integer
            ## 
            def warnings
                return @warnings
            end
            ## 
            ## Sets the warnings property value. The aggregate count of warnings generated by activities during this run.
            ## @param value Value to set for the warnings property.
            ## @return a void
            ## 
            def warnings=(value)
                @warnings = value
            end
        end
    end
end
