module MicrosoftGraphBeta
    module Models
        NetworkaccessRegion = {
            EastUS: :EastUS,
            EastUS2: :EastUS2,
            WestUS: :WestUS,
            WestUS2: :WestUS2,
            WestUS3: :WestUS3,
            CentralUS: :CentralUS,
            NorthCentralUS: :NorthCentralUS,
            SouthCentralUS: :SouthCentralUS,
            NorthEurope: :NorthEurope,
            WestEurope: :WestEurope,
            FranceCentral: :FranceCentral,
            GermanyWestCentral: :GermanyWestCentral,
            SwitzerlandNorth: :SwitzerlandNorth,
            UkSouth: :UkSouth,
            CanadaEast: :CanadaEast,
            CanadaCentral: :CanadaCentral,
            SouthAfricaWest: :SouthAfricaWest,
            SouthAfricaNorth: :SouthAfricaNorth,
            UaeNorth: :UaeNorth,
            AustraliaEast: :AustraliaEast,
            WestCentralUS: :WestCentralUS,
            CentralIndia: :CentralIndia,
            SouthEastAsia: :SouthEastAsia,
            SwedenCentral: :SwedenCentral,
            SouthIndia: :SouthIndia,
            AustraliaSouthEast: :AustraliaSouthEast,
            KoreaCentral: :KoreaCentral,
            PolandCentral: :PolandCentral,
            BrazilSouth: :BrazilSouth,
            JapanEast: :JapanEast,
            JapanWest: :JapanWest,
            UnknownFutureValue: :UnknownFutureValue,
            KoreaSouth: :KoreaSouth,
        }
    end
end
