module MicrosoftGraphBeta::Models
    RecommendationType = {
        AdfsAppsMigration: :AdfsAppsMigration,
        EnableDesktopSSO: :EnableDesktopSSO,
        EnablePHS: :EnablePHS,
        EnableProvisioning: :EnableProvisioning,
        SwitchFromPerUserMFA: :SwitchFromPerUserMFA,
        TenantMFA: :TenantMFA,
        ThirdPartyApps: :ThirdPartyApps,
        TurnOffPerUserMFA: :TurnOffPerUserMFA,
        UseAuthenticatorApp: :UseAuthenticatorApp,
        UseMyApps: :UseMyApps,
        StaleApps: :StaleApps,
        StaleAppCreds: :StaleAppCreds,
        ApplicationCredentialExpiry: :ApplicationCredentialExpiry,
        ServicePrincipalKeyExpiry: :ServicePrincipalKeyExpiry,
        AdminMFAV2: :AdminMFAV2,
        BlockLegacyAuthentication: :BlockLegacyAuthentication,
        IntegratedApps: :IntegratedApps,
        MfaRegistrationV2: :MfaRegistrationV2,
        PwagePolicyNew: :PwagePolicyNew,
        PasswordHashSync: :PasswordHashSync,
        OneAdmin: :OneAdmin,
        RoleOverlap: :RoleOverlap,
        SelfServicePasswordReset: :SelfServicePasswordReset,
        SigninRiskPolicy: :SigninRiskPolicy,
        UserRiskPolicy: :UserRiskPolicy,
        VerifyAppPublisher: :VerifyAppPublisher,
        PrivateLinkForAAD: :PrivateLinkForAAD,
        AppRoleAssignmentsGroups: :AppRoleAssignmentsGroups,
        AppRoleAssignmentsUsers: :AppRoleAssignmentsUsers,
        ManagedIdentity: :ManagedIdentity,
        OverprivilegedApps: :OverprivilegedApps,
        UnknownFutureValue: :UnknownFutureValue,
    }
end
