require 'microsoft_kiota_abstractions'
require_relative '../microsoft_graph_beta'
require_relative './models'

module MicrosoftGraphBeta
    module Models
        class WebauthnPublicKeyCredentialCreationOptions
            include MicrosoftKiotaAbstractions::AdditionalDataHolder, MicrosoftKiotaAbstractions::Parsable
            ## 
            # Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            @additional_data
            ## 
            # Attestation preference for the Microsoft Entra ID relying party.
            @attestation
            ## 
            # Properties of WebAuthn authenticators allowed to be used for authentication in Microsoft Entra ID.
            @authenticator_selection
            ## 
            # A challenge generated by Microsoft Entra ID and sent back with the registration request to prevent replay attacks.
            @challenge
            ## 
            # List of credentials blocked for creations in Microsoft Entra ID.
            @exclude_credentials
            ## 
            # Additional processing required by Microsoft Entra ID for the client and WebAuthn authenticator. For example, Microsoft Entra ID might require that particular information be returned in the attestation object.
            @extensions
            ## 
            # The OdataType property
            @odata_type
            ## 
            # A set of preferred credential properties for the creation of a new public key credential in Microsoft Entra ID.
            @pub_key_cred_params
            ## 
            # Information about the relying party (Microsoft Entra ID) responsible for the request.
            @rp
            ## 
            # The time in milliseconds that the client is willing to wait for the credential creation operation to complete.
            @timeout
            ## 
            # Information about the user account for which the credential is generated.
            @user
            ## 
            ## Gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            ## @return a i_dictionary
            ## 
            def additional_data
                return @additional_data
            end
            ## 
            ## Sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
            ## @param value Value to set for the AdditionalData property.
            ## @return a void
            ## 
            def additional_data=(value)
                @additional_data = value
            end
            ## 
            ## Gets the attestation property value. Attestation preference for the Microsoft Entra ID relying party.
            ## @return a string
            ## 
            def attestation
                return @attestation
            end
            ## 
            ## Sets the attestation property value. Attestation preference for the Microsoft Entra ID relying party.
            ## @param value Value to set for the attestation property.
            ## @return a void
            ## 
            def attestation=(value)
                @attestation = value
            end
            ## 
            ## Gets the authenticatorSelection property value. Properties of WebAuthn authenticators allowed to be used for authentication in Microsoft Entra ID.
            ## @return a webauthn_authenticator_selection_criteria
            ## 
            def authenticator_selection
                return @authenticator_selection
            end
            ## 
            ## Sets the authenticatorSelection property value. Properties of WebAuthn authenticators allowed to be used for authentication in Microsoft Entra ID.
            ## @param value Value to set for the authenticatorSelection property.
            ## @return a void
            ## 
            def authenticator_selection=(value)
                @authenticator_selection = value
            end
            ## 
            ## Gets the challenge property value. A challenge generated by Microsoft Entra ID and sent back with the registration request to prevent replay attacks.
            ## @return a string
            ## 
            def challenge
                return @challenge
            end
            ## 
            ## Sets the challenge property value. A challenge generated by Microsoft Entra ID and sent back with the registration request to prevent replay attacks.
            ## @param value Value to set for the challenge property.
            ## @return a void
            ## 
            def challenge=(value)
                @challenge = value
            end
            ## 
            ## Instantiates a new WebauthnPublicKeyCredentialCreationOptions and sets the default values.
            ## @return a void
            ## 
            def initialize()
                @additional_data = Hash.new
            end
            ## 
            ## Creates a new instance of the appropriate class based on discriminator value
            ## @param parse_node The parse node to use to read the discriminator value and create the object
            ## @return a webauthn_public_key_credential_creation_options
            ## 
            def self.create_from_discriminator_value(parse_node)
                raise StandardError, 'parse_node cannot be null' if parse_node.nil?
                return WebauthnPublicKeyCredentialCreationOptions.new
            end
            ## 
            ## Gets the excludeCredentials property value. List of credentials blocked for creations in Microsoft Entra ID.
            ## @return a webauthn_public_key_credential_descriptor
            ## 
            def exclude_credentials
                return @exclude_credentials
            end
            ## 
            ## Sets the excludeCredentials property value. List of credentials blocked for creations in Microsoft Entra ID.
            ## @param value Value to set for the excludeCredentials property.
            ## @return a void
            ## 
            def exclude_credentials=(value)
                @exclude_credentials = value
            end
            ## 
            ## Gets the extensions property value. Additional processing required by Microsoft Entra ID for the client and WebAuthn authenticator. For example, Microsoft Entra ID might require that particular information be returned in the attestation object.
            ## @return a webauthn_authentication_extensions_client_inputs
            ## 
            def extensions
                return @extensions
            end
            ## 
            ## Sets the extensions property value. Additional processing required by Microsoft Entra ID for the client and WebAuthn authenticator. For example, Microsoft Entra ID might require that particular information be returned in the attestation object.
            ## @param value Value to set for the extensions property.
            ## @return a void
            ## 
            def extensions=(value)
                @extensions = value
            end
            ## 
            ## The deserialization information for the current model
            ## @return a i_dictionary
            ## 
            def get_field_deserializers()
                return {
                    "attestation" => lambda {|n| @attestation = n.get_string_value() },
                    "authenticatorSelection" => lambda {|n| @authenticator_selection = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnAuthenticatorSelectionCriteria.create_from_discriminator_value(pn) }) },
                    "challenge" => lambda {|n| @challenge = n.get_string_value() },
                    "excludeCredentials" => lambda {|n| @exclude_credentials = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnPublicKeyCredentialDescriptor.create_from_discriminator_value(pn) }) },
                    "extensions" => lambda {|n| @extensions = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnAuthenticationExtensionsClientInputs.create_from_discriminator_value(pn) }) },
                    "@odata.type" => lambda {|n| @odata_type = n.get_string_value() },
                    "pubKeyCredParams" => lambda {|n| @pub_key_cred_params = n.get_collection_of_object_values(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnPublicKeyCredentialParameters.create_from_discriminator_value(pn) }) },
                    "rp" => lambda {|n| @rp = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnPublicKeyCredentialRpEntity.create_from_discriminator_value(pn) }) },
                    "timeout" => lambda {|n| @timeout = n.get_number_value() },
                    "user" => lambda {|n| @user = n.get_object_value(lambda {|pn| MicrosoftGraphBeta::Models::WebauthnPublicKeyCredentialUserEntity.create_from_discriminator_value(pn) }) },
                }
            end
            ## 
            ## Gets the @odata.type property value. The OdataType property
            ## @return a string
            ## 
            def odata_type
                return @odata_type
            end
            ## 
            ## Sets the @odata.type property value. The OdataType property
            ## @param value Value to set for the @odata.type property.
            ## @return a void
            ## 
            def odata_type=(value)
                @odata_type = value
            end
            ## 
            ## Gets the pubKeyCredParams property value. A set of preferred credential properties for the creation of a new public key credential in Microsoft Entra ID.
            ## @return a webauthn_public_key_credential_parameters
            ## 
            def pub_key_cred_params
                return @pub_key_cred_params
            end
            ## 
            ## Sets the pubKeyCredParams property value. A set of preferred credential properties for the creation of a new public key credential in Microsoft Entra ID.
            ## @param value Value to set for the pubKeyCredParams property.
            ## @return a void
            ## 
            def pub_key_cred_params=(value)
                @pub_key_cred_params = value
            end
            ## 
            ## Gets the rp property value. Information about the relying party (Microsoft Entra ID) responsible for the request.
            ## @return a webauthn_public_key_credential_rp_entity
            ## 
            def rp
                return @rp
            end
            ## 
            ## Sets the rp property value. Information about the relying party (Microsoft Entra ID) responsible for the request.
            ## @param value Value to set for the rp property.
            ## @return a void
            ## 
            def rp=(value)
                @rp = value
            end
            ## 
            ## Serializes information the current object
            ## @param writer Serialization writer to use to serialize this model
            ## @return a void
            ## 
            def serialize(writer)
                raise StandardError, 'writer cannot be null' if writer.nil?
                writer.write_string_value("attestation", @attestation)
                writer.write_object_value("authenticatorSelection", @authenticator_selection)
                writer.write_string_value("challenge", @challenge)
                writer.write_collection_of_object_values("excludeCredentials", @exclude_credentials)
                writer.write_object_value("extensions", @extensions)
                writer.write_string_value("@odata.type", @odata_type)
                writer.write_collection_of_object_values("pubKeyCredParams", @pub_key_cred_params)
                writer.write_object_value("rp", @rp)
                writer.write_number_value("timeout", @timeout)
                writer.write_object_value("user", @user)
                writer.write_additional_data(@additional_data)
            end
            ## 
            ## Gets the timeout property value. The time in milliseconds that the client is willing to wait for the credential creation operation to complete.
            ## @return a integer
            ## 
            def timeout
                return @timeout
            end
            ## 
            ## Sets the timeout property value. The time in milliseconds that the client is willing to wait for the credential creation operation to complete.
            ## @param value Value to set for the timeout property.
            ## @return a void
            ## 
            def timeout=(value)
                @timeout = value
            end
            ## 
            ## Gets the user property value. Information about the user account for which the credential is generated.
            ## @return a webauthn_public_key_credential_user_entity
            ## 
            def user
                return @user
            end
            ## 
            ## Sets the user property value. Information about the user account for which the credential is generated.
            ## @param value Value to set for the user property.
            ## @return a void
            ## 
            def user=(value)
                @user = value
            end
        end
    end
end
