require_relative 'update_device_profile_assignment_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::DepOnboardingSettings::Item::EnrollmentProfiles::Item::MicrosoftGraphUpdateDeviceProfileAssignment
end
