module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceRole::AccessPackageResource::AccessPackageResourceScopes::Count
end
