require_relative 'import_device_identity_list_post_request_body'
require_relative 'import_device_identity_list_response'
module MicrosoftGraphBeta::DeviceManagement::ImportedDeviceIdentities::ImportDeviceIdentityList
end
