require_relative 'get_device_configuration_policy_settings_summary_report_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::Reports::MicrosoftGraphGetDeviceConfigurationPolicySettingsSummaryReport
end
