require_relative 'get_web_parts_by_position_post_request_body'
require_relative 'get_web_parts_by_position_response'
module MicrosoftGraphBeta::Sites::Item::Pages::Item::MicrosoftGraphGetWebPartsByPosition
end
