module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceScope::AccessPackageResource::AccessPackageResourceRoles
end
