require_relative 'get_applicable_policy_requirements_response'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageCatalogs::Item::AccessPackages::Item::GetApplicablePolicyRequirements
end
