require_relative 'send_custom_notification_to_company_portal_post_request_body'
module MicrosoftGraphBeta::DeviceManagement::ComanagedDevices::Item::MicrosoftGraphSendCustomNotificationToCompanyPortal
end
