require_relative 'set_scheduled_actions_post_request_body'
require_relative 'set_scheduled_actions_response'
module MicrosoftGraphBeta::DeviceManagement::CompliancePolicies::Item::SetScheduledActions
end
