require_relative 'query_by_platform_type_post_request_body'
require_relative 'query_by_platform_type_response'
module MicrosoftGraphBeta::DeviceManagement::ResourceAccessProfiles::QueryByPlatformType
end
