require_relative 'create_enrollment_notification_configuration_post_request_body'
module MicrosoftGraphBeta::Users::Item::DeviceEnrollmentConfigurations::CreateEnrollmentNotificationConfiguration
end
