require_relative 'get_global_script_highest_available_version_response'
module MicrosoftGraphBeta::DeviceManagement::DeviceHealthScripts::Item::MicrosoftGraphGetGlobalScriptHighestAvailableVersion
end
