require_relative 'update_allowed_combinations_post_request_body'
module MicrosoftGraphBeta::Identity::ConditionalAccess::AuthenticationStrength::Policies::Item::MicrosoftGraphUpdateAllowedCombinations
end
