require_relative 'assigned_principals_with_transitivedirectory_scope_type_directory_scope_type_directory_scope_id_directory_scope_id_response'
module MicrosoftGraphBeta::RoleManagement::DeviceManagement::RoleDefinitions::Item::AssignedPrincipalsWithTransitivedirectoryScopeTypeDirectoryScopeTypeDirectoryScopeIdDirectoryScopeId
end
