require_relative 'get_health_metrics_post_request_body'
require_relative 'get_health_metrics_response'
module MicrosoftGraphBeta::DeviceManagement::CertificateConnectorDetails::Item::MicrosoftGraphGetHealthMetrics
end
