require_relative 'filter_by_current_user_with_on_response'
module MicrosoftGraphBeta::RoleManagement::EntitlementManagement::RoleEligibilityScheduleInstances::MicrosoftGraphFilterByCurrentUserWithOn
end
