require_relative 'has_payload_links_post_request_body'
require_relative 'has_payload_links_response'
module MicrosoftGraphBeta::Users::Item::DeviceEnrollmentConfigurations::MicrosoftGraphHasPayloadLinks
end
