require_relative 'import_apple_device_identity_list_post_request_body'
require_relative 'import_apple_device_identity_list_response'
module MicrosoftGraphBeta::DeviceManagement::DepOnboardingSettings::Item::ImportedAppleDeviceIdentities::ImportAppleDeviceIdentityList
end
