require_relative 'get_applicable_policy_requirements_response'
module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackage::GetApplicablePolicyRequirements
end
