module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceScope::AccessPackageResource::AccessPackageResourceRoles::Item::AccessPackageResource::AccessPackageResourceScopes::Item
end
