module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignments::Item::AccessPackage::AccessPackageResourceRoleScopes::Item::AccessPackageResourceRole::AccessPackageResource
end
