module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceScope::AccessPackageResource::AccessPackageResourceScopes::Item
end
