module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackageAssignmentResourceRoles::Item::AccessPackageResourceRole::AccessPackageResource::AccessPackageResourceRoles::Item
end
