require_relative 'change_deployment_status_post_request_body'
module MicrosoftGraphBeta::TenantRelationships::ManagedTenants::ManagementTemplateStepVersions::Item::Deployments::Item::MicrosoftGraphManagedTenantsChangeDeploymentStatus
end
