require_relative 'update_global_script_post_request_body'
require_relative 'update_global_script_response'
module MicrosoftGraphBeta::DeviceManagement::DeviceHealthScripts::Item::UpdateGlobalScript
end
