name: Ruby

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['2.7', '3.0', '3.1', head, jruby, jruby-head, truffleruby, truffleruby-head]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: 'latest'
          cache-version: 1
      - name: Run tests
        run: bundle exec rake
      - name: Upload artifacts for ruby version 3 and ubuntu
        if: ${{ matrix.os == 'ubuntu-latest'  && matrix.ruby-version == '3.1'}}
        uses: actions/upload-artifact@v3
        with:
          name: drop
          path: |
            ./Gemfile.lock
            ./README.md
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: 'latest'
          cache-version: 1
      - run: bundle exec rake
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.PUBLISH_GH_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
  # deploy_prod:
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  #   environment:
  #     name: production_feeds
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.1'
  #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  #     - run: bundle exec rake
  #     - name: Publish to RubyGems
  #       run: |
  #         mkdir -p $HOME/.gem
  #         touch $HOME/.gem/credentials
  #         chmod 0600 $HOME/.gem/credentials
  #         printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
  #         gem build *.gemspec
  #         gem push *.gem
  #       env:
  #         GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}" TODO: Token for rubyGems.org

