module MicrosoftGraphBeta::IdentityGovernance::EntitlementManagement::AccessPackages::Item::AccessPackageResourceRoleScopes::Item::AccessPackageResourceScope::AccessPackageResource::AccessPackageResourceScopes
end
